### PR TITLE
OCaml tsdl example

### PR DESCRIPTION
**Pull request by bholten**
I've added a fairly idiomatic `tsdl` example based on your `ocaml` branch with binding operators.

I'm on debian, if you have any issues running it, please let me know! The `-thread` is a little sus to me but I don't have another system to test it on atm.

### CODE REVIEW

**Comment by xyproto** [comment]
Thanks for the pull request! I'll test it on Arch and then merge it in.

**Comment by xyproto** [comment]
Merged.

**Comment by xyproto** [comment]
I see that `Sdl.create_window_and_renderer` does not support setting a window title, but creating a window and then a renderer like in [this example](https://github.com/dbuenzli/tsdl/blob/master/test/test.ml#L443) was slightly more involved, and increases the indentation levels. Do you happen to know how to create a window and then a renderer, in the same style as the program you wrote?

**Comment by bholten** [comment]
Yes! `Sdl.create_window` returns `window result`, so it can be `let*` into the normal chain. The let-bindings are essentially like Haskell `do` or Scala `for` blocks -- in this case, the `run` function is monadic under `result`.

So it will just look something like this:

```ocaml
let* _ = Sdl.init Sdl.Init.everything in
let* w = Sdl.create_window "Hello World!" ~w:620 ~h:387 (* omitting stuff... *) in 
let* r = Sdl.create_renderer w (* omitting stuff ... *) in 
(* rest is unchanged *)
``` 

I will make a PR later tonight when I get home, it would be good to have all the options as a reference (there is `x`, `y`, `Renderer.flags`, and I can't remember what else). It's also a more real-life example, that's much more similar to what I do for my hobby games in emulators.

**Comment by xyproto** [comment]
Excellent, thanks! 🙂

**Pull request merged**
