### PR TITLE
Add Linux to the CI workflow for Ada

### PR DESCRIPTION
**Pull request by xyproto**
Re-add `ubuntu-latest` to the Ada CI configuration.

### CODE REVIEW

**Comment by xyproto** [comment]
@simonjwright When `ubuntu-latest` is re-added to the CI configuration, the Ada build stops working.

**Comment by simonjwright** [comment]
Looking into it ...

**Comment by simonjwright** [comment]
I posted [this issue](https://github.com/alire-project/alire/issues/1548). Will carry on looking for a solution.

**Comment by xyproto** [comment]
Cool, thanks. I am curious to see how Alire upstream will respond.

**Comment by xyproto** [comment]
I had no luck building + running the Ada example on Arch Linux. I moved it to the `ada` branch, for now.

**Pull request closed without merging**
